apiVersion: v1
kind: Pod
metadata:
  name: node-mongo-todo
  labels:
    name: node-mongo-todo
spec:
  containers:
    - name: node-mongo-todo
      image: dev4dar/node-mongo-todo
      ports:
        - containerPort: 8080
      env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: mongo-todo-db-url
              key: DB_URL

