
apiVersion: v1
kind: Service
metadata:
  name: node-mongo-todo-service
  labels:
    app: node-mongo-todo-service
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    name: node-mongo-todo
  type: LoadBalancer

